services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./docker/php/xdebug.log:/var/log/xdebug.log
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flow
      MYSQL_USER: flow
      MYSQL_PASSWORD: flow
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
